// Code generated by go-swagger; DO NOT EDIT.

package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetCharacterListParams creates a new GetCharacterListParams object
//
// There are no default values defined in the spec.
func NewGetCharacterListParams() GetCharacterListParams {

	return GetCharacterListParams{}
}

// GetCharacterListParams contains all the bound params for the get character list operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCharacterList
type GetCharacterListParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*認証トークン
	  Required: true
	  In: header
	*/
	XToken string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCharacterListParams() beforehand.
func (o *GetCharacterListParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXToken(r.Header[http.CanonicalHeaderKey("x-token")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXToken binds and validates parameter XToken from header.
func (o *GetCharacterListParams) bindXToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("x-token", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("x-token", "header", raw); err != nil {
		return err
	}
	o.XToken = raw

	return nil
}
