// Code generated by go-swagger; DO NOT EDIT.

package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GuiltyMorishita/techtrain-mission/models"
)

// GetCharacterListOKCode is the HTTP code returned for type GetCharacterListOK
const GetCharacterListOKCode int = 200

/*GetCharacterListOK A successful response.

swagger:response getCharacterListOK
*/
type GetCharacterListOK struct {

	/*
	  In: Body
	*/
	Payload *models.CharacterListResponse `json:"body,omitempty"`
}

// NewGetCharacterListOK creates GetCharacterListOK with default headers values
func NewGetCharacterListOK() *GetCharacterListOK {

	return &GetCharacterListOK{}
}

// WithPayload adds the payload to the get character list o k response
func (o *GetCharacterListOK) WithPayload(payload *models.CharacterListResponse) *GetCharacterListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get character list o k response
func (o *GetCharacterListOK) SetPayload(payload *models.CharacterListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharacterListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
