// Code generated by go-swagger; DO NOT EDIT.

// Package restapi TechTrain MISSION Game API
//
//  TechTrain MISSION ゲームAPI入門仕様
//   まずはこのAPI仕様に沿って機能を実装してみましょう。
//
//   この画面の各APIの「Try it out」->「Execute」を利用することで
//   ローカル環境で起動中のAPIにAPIリクエストをすることができます。
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
