// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/GuiltyMorishita/techtrain-mission/models"
)

// PostUserCreateOKCode is the HTTP code returned for type PostUserCreateOK
const PostUserCreateOKCode int = 200

/*PostUserCreateOK A successful response.

swagger:response postUserCreateOK
*/
type PostUserCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserCreateResponse `json:"body,omitempty"`
}

// NewPostUserCreateOK creates PostUserCreateOK with default headers values
func NewPostUserCreateOK() *PostUserCreateOK {

	return &PostUserCreateOK{}
}

// WithPayload adds the payload to the post user create o k response
func (o *PostUserCreateOK) WithPayload(payload *models.UserCreateResponse) *PostUserCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user create o k response
func (o *PostUserCreateOK) SetPayload(payload *models.UserCreateResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
