// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUserUpdateOKCode is the HTTP code returned for type PutUserUpdateOK
const PutUserUpdateOKCode int = 200

/*PutUserUpdateOK A successful response.

swagger:response putUserUpdateOK
*/
type PutUserUpdateOK struct {
}

// NewPutUserUpdateOK creates PutUserUpdateOK with default headers values
func NewPutUserUpdateOK() *PutUserUpdateOK {

	return &PutUserUpdateOK{}
}

// WriteResponse to the client
func (o *PutUserUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
