// Code generated by go-swagger; DO NOT EDIT.

package gacha

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/GuiltyMorishita/techtrain-mission/models"
)

// NewPostGachaDrawParams creates a new PostGachaDrawParams object
//
// There are no default values defined in the spec.
func NewPostGachaDrawParams() PostGachaDrawParams {

	return PostGachaDrawParams{}
}

// PostGachaDrawParams contains all the bound params for the post gacha draw operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostGachaDraw
type PostGachaDrawParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Request Body
	  Required: true
	  In: body
	*/
	Body *models.GachaDrawRequest
	/*認証トークン
	  Required: true
	  In: header
	*/
	XToken string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostGachaDrawParams() beforehand.
func (o *PostGachaDrawParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.GachaDrawRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}

	if err := o.bindXToken(r.Header[http.CanonicalHeaderKey("x-token")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXToken binds and validates parameter XToken from header.
func (o *PostGachaDrawParams) bindXToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("x-token", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("x-token", "header", raw); err != nil {
		return err
	}
	o.XToken = raw

	return nil
}
